[package]
name = "kalaxia-api"
version = "0.1.0"
authors = ["Axel Venet <kern046@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9.0"
actix-web = "2.0"
actix-web-actors = "2.0"
actix-rt = "1.1"
actix-files = "0.2.1"
rand = "0.7.3"
log = "0.4.8"
serde = "1.0.106"
uuid = { version = "0.8", features = ["v4", "serde"] }
jsonwebtoken = "7.1.0"
futures = "0.3.4"
actix-service = "1.0.5"
serde_json = "1.0.51"
