version: '3.5'

networks:
    api:
        driver: bridge

services:
    api:
        container_name: kalaxia_v2_api
        build: 
            context: .
            args:
                - FEATURES=${FEATURES}
        env_file:
            - kalaxia.env
        volumes:
            - "./var/ssl:/var/ssl"
        ports:
            - "80:80"
            - "443:443"